### ISSUE TITLE
Display venue information prominently.

### ISSUE THREAD

**Issue by Mariatta** [pycascades/www.pycascades.com#95]
If we go to https://2020.pycascades.com/ and scroll up and down, Revolution Hall is not mentioned on the page.

If we then go to > About > The conference, Revolution Hall is also not mentioned on the page.

Revolution Hall is only mentioned on ticketing page.

It would be great if we have more information about the venue and address in our homepage.

Thanks.

**Comment by EstiShay** [comment]
Yes to adding the venue to the home page, specifically on the left of this screenshot, maybe just change that text to say "Revolution Hall in Portland, Oregon": 
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/16904847/69456732-38b93d80-0d20-11ea-90cf-c90174433883.png">

**Comment by EstiShay** [comment]
Yes to adding the [Venue page](https://github.com/pycascades/www.pycascades.com/blob/2019/content/venue/contents.lr) to the website. 

body:

Revolution Hall
1300 SE Stark Street, Portland, OR

Revolution Hall is a performing arts center and concert venue at the heart of the iconic Washington High School building, in Portland's Buckman neighborhood. Built in 1906, the school was closed in 1981 due to low enrollment, and since 2013 it has been completely renovated and restored to accommodate offices, bars, two cafes, flex-use space + the historic auditorium.

- [Revolution Hall](https://www.revolutionhall.com/)
- [Public Transit & Parking](https://www.revolutionhall.com/venue-information/parking-public-transit/)
- Check out their [Instagram](https://www.instagram.com/revolutionhall/)

**Comment by roadsideseb** [comment]
I've opened #98 to resolve this.

**Comment by roadsideseb** [comment]
Resolved by #98
